# Docker para desarrollo
FROM golang:1.14.3-buster

WORKDIR /go/src/github.com/nmarsollier/imagego
COPY . ./
RUN go install

ENV REDIS_URL host.docker.internal:6379
ENV RABBIT_URL amqp://host.docker.internal
ENV AUTH_SERVICE_URL http://host.docker.internal:3000

# Puerto de Image Service
EXPOSE 3001

CMD ["imagego"]

