openapi: 3.0.0

info:
  title: Imagenes en Go
  description: Microservicio de Imagenes
  version: "1.0.0"
  contact:
    name: Nestor Marsollier
    email: nmarsollier@gmail.com

servers:
  - url: http://localhost:3001/
    description: Microservicio local

paths:
  /v1/image:
    post:
      description: Crear Imagen
      summary: Crea una nueva imagen
      security:
        - authHeader: []
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/PostImageRequest'
      responses: 
        200:
          description: Id de la nueva imagen
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/PostImageResponse'
        400:
          description: Error de validacion
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ParamValidationErrors'
        500:
          description: Error de validacion
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/OtherErrors'

components:
  securitySchemes:
    authHeader:
      type: apiKey
      in: header
      name: Authentication
  schemas:
    PostImageResponse:
      title: Imagen Id
      type: object
      description: Respuesta al crear imagenes
      properties:
        "id":
          type: string
    PostImageRequest:
      title: Body para crear una nueva imagen
      type: object
      properties:
        "image":
          description: Imagen en Base64
          type: string
      required: ["image"]
    ParamValidationErrors:
      title: Error de validacion de parametros
      type: object
      properties:
        "messages":
          type: array
          items:
            $ref: '#/components/schemas/PathError'
    PathError:
      title: Path del error
      type: object
      properties:
        "path":
          type: string
          description: Path del error
        "messages":
          type: string
          description: Problema
    OtherErrors:
      title: Otros errores
      type: object
      properties:
        "error":
          type: string
          description: Mensaje del error
