package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"

	"github.com/nmarsollier/imagego/graph/model"
	"github.com/nmarsollier/imagego/graph/resolvers"
)

// FindImageByID is the resolver for the findImageByID field.
func (r *entityResolver) FindImageByID(ctx context.Context, id string) (*model.Image, error) {
	return resolvers.FindImageByID(ctx, id, model.ImageSizeOriginal)
}

// Entity returns model.EntityResolver implementation.
func (r *Resolver) Entity() model.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
