package schema

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"

	"github.com/nmarsollier/imagego/internal/graph/model"
)

// FindImageByID is the resolver for the findImageByID field.
func (r *entityResolver) FindImageByID(ctx context.Context, id string) (*model.Image, error) {
	panic(fmt.Errorf("not implemented: FindImageByID - findImageByID"))
}

// Entity returns model.EntityResolver implementation.
func (r *Resolver) Entity() model.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
