// Code generated by MockGen. DO NOT EDIT.
// Source: ./db/dao.go

// Package db is a generated GoMock package.
package db

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockImageDao is a mock of ImageDao interface.
type MockImageDao struct {
	ctrl     *gomock.Controller
	recorder *MockImageDaoMockRecorder
}

// MockImageDaoMockRecorder is the mock recorder for MockImageDao.
type MockImageDaoMockRecorder struct {
	mock *MockImageDao
}

// NewMockImageDao creates a new mock instance.
func NewMockImageDao(ctrl *gomock.Controller) *MockImageDao {
	mock := &MockImageDao{ctrl: ctrl}
	mock.recorder = &MockImageDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageDao) EXPECT() *MockImageDaoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockImageDao) Get(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockImageDaoMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockImageDao)(nil).Get), key)
}

// Set mocks base method.
func (m *MockImageDao) Set(key, value string, expiration time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value, expiration)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Set indicates an expected call of Set.
func (mr *MockImageDaoMockRecorder) Set(key, value, expiration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockImageDao)(nil).Set), key, value, expiration)
}
