basePath: /v1
definitions:
  errs.ValidationErr:
    properties:
      messages:
        items:
          $ref: '#/definitions/errs.errField'
        type: array
    type: object
  errs.errField:
    properties:
      message:
        type: string
      path:
        type: string
    type: object
  rbt.InputMessage-string:
    properties:
      correlation_id:
        example: "123123"
        type: string
      message:
        type: string
    type: object
  rest.NewImageResponse:
    properties:
      id:
        type: string
    required:
    - id
    type: object
  rest.NewRequest:
    properties:
      image:
        type: string
    required:
    - image
    type: object
  rst.ErrorData:
    properties:
      error:
        type: string
    type: object
host: localhost:3001
info:
  contact:
    email: nmarsollier@gmail.com
    name: Nestor Marsollier
  description: Microservicio de Imagenes.
  title: ImageGo
  version: "1.0"
paths:
  /images/:imageID:
    get:
      consumes:
      - application/json
      description: Gets an image from the server in base64 format
      parameters:
      - description: Logging Correlation Id
        in: header
        name: correlation_id
        required: true
        type: string
      - description: '[160|320|640|800|1024|1200]'
        in: path
        name: Size
        required: true
        type: string
      - description: Image ID
        in: path
        name: imageID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Image Information
          schema: {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rst.ErrorData'
      summary: Get image
      tags:
      - Image
  /images/:imageID/jpeg:
    get:
      consumes:
      - application/json
      description: Gets an image from the server in jpeg format.
      parameters:
      - description: Logging Correlation Id
        in: header
        name: correlation_id
        required: true
        type: string
      - description: '[160|320|640|800|1024|1200]'
        in: path
        name: Size
        required: true
        type: string
      - description: Image ID
        in: path
        name: imageID
        required: true
        type: string
      produces:
      - image/jpeg
      responses:
        "200":
          description: Image
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rst.ErrorData'
      summary: Get jpeg
      tags:
      - Image
  /images/create:
    post:
      consumes:
      - application/json
      description: Adds a new image to the server.
      parameters:
      - description: Image in base64
        in: body
        name: image
        required: true
        schema:
          $ref: '#/definitions/rest.NewRequest'
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: Logging Correlation Id
        in: header
        name: correlation_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Image
          schema:
            $ref: '#/definitions/rest.NewImageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rst.ErrorData'
      summary: Save image
      tags:
      - Image
  /rabbit/logout:
    get:
      consumes:
      - application/json
      description: Escucha de mensajes logout desde auth.
      parameters:
      - description: Estructura general del mensage
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/rbt.InputMessage-string'
      produces:
      - application/json
      responses: {}
      summary: Mensage Rabbit logout
      tags:
      - Rabbit
swagger: "2.0"
