basePath: /v1
definitions:
  errs.ValidationErr:
    properties:
      messages:
        items:
          $ref: '#/definitions/errs.errField'
        type: array
    type: object
  errs.errField:
    properties:
      message:
        type: string
      path:
        type: string
    type: object
  image.Image:
    properties:
      id:
        type: string
      image:
        type: string
    required:
    - id
    - image
    type: object
  rabbit.message:
    properties:
      correlation_id:
        example: "123123"
        type: string
      message:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbklEIjoiNjZiNjBlYzhlMGYzYzY4OTUzMzJlOWNmIiwidXNlcklEIjoiNjZhZmQ3ZWU4YTBhYjRjZjQ0YTQ3NDcyIn0.who7upBctOpmlVmTvOgH1qFKOHKXmuQCkEjMV3qeySg
        type: string
    type: object
  rest.NewImageResponse:
    properties:
      id:
        type: string
    required:
    - id
    type: object
  rest.NewRequest:
    properties:
      image:
        type: string
    required:
    - image
    type: object
  server.ErrorData:
    properties:
      error:
        type: string
    type: object
host: localhost:3001
info:
  contact:
    email: nmarsollier@gmail.com
    name: Nestor Marsollier
  description: Microservicio de Imagenes.
  title: ImageGo
  version: "1.0"
paths:
  /rabbit/logout:
    get:
      consumes:
      - application/json
      description: Listens for logout messages from auth.
      parameters:
      - description: General message structure
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/rabbit.message'
      produces:
      - application/json
      responses: {}
      summary: Rabbit Message
      tags:
      - Rabbit
  /v1/image:
    post:
      consumes:
      - application/json
      description: Adds a new image to the server.
      parameters:
      - description: Image in base64
        in: body
        name: image
        required: true
        schema:
          $ref: '#/definitions/rest.NewRequest'
      - description: bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: Logging Correlation Id
        in: header
        name: correlation_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Image
          schema:
            $ref: '#/definitions/rest.NewImageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/server.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/server.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorData'
      summary: Save image
      tags:
      - Image
  /v1/image/:imageID:
    get:
      consumes:
      - application/json
      description: Gets an image from the server in base64 format
      parameters:
      - description: Logging Correlation Id
        in: header
        name: correlation_id
        required: true
        type: string
      - description: '[160|320|640|800|1024|1200]'
        in: path
        name: Size
        required: true
        type: string
      - description: Image ID
        in: path
        name: imageID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Image Information
          schema:
            $ref: '#/definitions/image.Image'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/server.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/server.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorData'
      summary: Get image
      tags:
      - Image
  /v1/image/:imageID/jpeg:
    get:
      consumes:
      - application/json
      description: Gets an image from the server in jpeg format.
      parameters:
      - description: Logging Correlation Id
        in: header
        name: correlation_id
        required: true
        type: string
      - description: '[160|320|640|800|1024|1200]'
        in: path
        name: Size
        required: true
        type: string
      - description: Image ID
        in: path
        name: imageID
        required: true
        type: string
      produces:
      - image/jpeg
      responses:
        "200":
          description: Image
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/server.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/server.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorData'
      summary: Get jpeg
      tags:
      - Image
swagger: "2.0"
