// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/security/repository.go

// Package mockgen is a generated GoMock package.
package mockgen

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	security "github.com/nmarsollier/imagego/internal/security"
)

// MockSecurityRepository is a mock of SecurityRepository interface.
type MockSecurityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityRepositoryMockRecorder
}

// MockSecurityRepositoryMockRecorder is the mock recorder for MockSecurityRepository.
type MockSecurityRepositoryMockRecorder struct {
	mock *MockSecurityRepository
}

// NewMockSecurityRepository creates a new mock instance.
func NewMockSecurityRepository(ctrl *gomock.Controller) *MockSecurityRepository {
	mock := &MockSecurityRepository{ctrl: ctrl}
	mock.recorder = &MockSecurityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityRepository) EXPECT() *MockSecurityRepositoryMockRecorder {
	return m.recorder
}

// CleanToken mocks base method.
func (m *MockSecurityRepository) CleanToken(token string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CleanToken", token)
}

// CleanToken indicates an expected call of CleanToken.
func (mr *MockSecurityRepositoryMockRecorder) CleanToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanToken", reflect.TypeOf((*MockSecurityRepository)(nil).CleanToken), token)
}

// GetRemoteToken mocks base method.
func (m *MockSecurityRepository) GetRemoteToken(token string) (*security.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemoteToken", token)
	ret0, _ := ret[0].(*security.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemoteToken indicates an expected call of GetRemoteToken.
func (mr *MockSecurityRepositoryMockRecorder) GetRemoteToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemoteToken", reflect.TypeOf((*MockSecurityRepository)(nil).GetRemoteToken), token)
}

// GetToken mocks base method.
func (m *MockSecurityRepository) GetToken(token string) (*security.User, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToken", token)
	ret0, _ := ret[0].(*security.User)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetToken indicates an expected call of GetToken.
func (mr *MockSecurityRepositoryMockRecorder) GetToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockSecurityRepository)(nil).GetToken), token)
}
